
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  chunk_target_size: 1536000
  chunk_block_size: 262144
  chunk_encoding: snappy

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/boltdb-cache
    cache_ttl: 24h
  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 1h
  allow_structured_metadata: false

chunk_store_config: {}

table_manager:
  retention_deletes_enabled: true
  retention_period: 1h

compactor:
  working_directory: /tmp/loki/compactor

common:
  path_prefix: /tmp/loki
